### ISSUE TITLE
Tests failing cannot find Anvil

### ISSUE THREAD

**Issue by Genysys** [gakonst/ethers-rs#1361]
**Version**
```
ethers-addressbook v0.1.0 (/Users/samueldare/Code/rust/ethers-rs/ethers-addressbook)
├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core)
ethers-contract v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-contract)
├── ethers-contract-abigen v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-contract/ethers-contract-abigen)
│   ├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
├── ethers-contract-derive v0.6.3 (proc-macro) (/Users/samueldare/Code/rust/ethers-rs/ethers-contract/ethers-contract-derive)
│   ├── ethers-contract-abigen v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-contract/ethers-contract-abigen) (*)
│   ├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
├── ethers-derive-eip712 v0.2.2 (proc-macro) (/Users/samueldare/Code/rust/ethers-rs/ethers-core/ethers-derive-eip712)
│   ├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
├── ethers-providers v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-providers)
│   ├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
├── ethers-contract-abigen v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-contract/ethers-contract-abigen) (*)
├── ethers-contract-derive v0.6.3 (proc-macro) (/Users/samueldare/Code/rust/ethers-rs/ethers-contract/ethers-contract-derive) (*)
├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
├── ethers-derive-eip712 v0.2.2 (proc-macro) (/Users/samueldare/Code/rust/ethers-rs/ethers-core/ethers-derive-eip712) (*)
├── ethers-middleware v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-middleware)
│   ├── ethers-contract v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-contract) (*)
│   ├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
│   ├── ethers-etherscan v0.2.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-etherscan)
│   │   ├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
│   │   ├── ethers-solc v0.3.0 (/Users/samueldare/Code/rust/ethers-rs/ethers-solc)
│   │   │   ├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
│   ├── ethers-providers v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-providers) (*)
│   ├── ethers-signers v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-signers)
│   │   ├── ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
│   │   ├── ethers-contract v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-contract) (*)
│   │   ├── ethers-derive-eip712 v0.2.2 (proc-macro) (/Users/samueldare/Code/rust/ethers-rs/ethers-core/ethers-derive-eip712) (*)
│   ├── ethers-providers v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-providers) (*)
│   ├── ethers-solc v0.3.0 (/Users/samueldare/Code/rust/ethers-rs/ethers-solc) (*)
├── ethers-providers v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-providers) (*)
├── ethers-signers v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-signers) (*)
├── ethers-solc v0.3.0 (/Users/samueldare/Code/rust/ethers-rs/ethers-solc) (*)
ethers-core v0.6.3 (/Users/samueldare/Code/rust/ethers-rs/ethers-core) (*)
ethers-etherscan v0.2.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-etherscan) (*)
ethers-middleware v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-middleware) (*)
ethers-providers v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-providers) (*)
ethers-signers v0.6.2 (/Users/samueldare/Code/rust/ethers-rs/ethers-signers) (*)
ethers-solc v0.3.0 (/Users/samueldare/Code/rust/ethers-rs/ethers-solc) (*)
```

**Platform**
Darwin Samuels-MacBook-Pro 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 x86_64

**Description**

When I run `cargo test`

I get following output

```
failures:

---- can_deploy_greeter stdout ----
thread 'can_deploy_greeter' panicked at 'couldnt start anvil: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ethers-core/src/utils/anvil.rs:168:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- can_send_struct_param stdout ----
thread 'can_send_struct_param' panicked at 'couldnt start anvil: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ethers-core/src/utils/anvil.rs:168:37

---- can_handle_underscore_functions stdout ----
thread 'can_handle_underscore_functions' panicked at 'couldnt start anvil: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ethers-core/src/utils/anvil.rs:168:37

---- can_abiencoderv2_output stdout ----
thread 'can_abiencoderv2_output' panicked at 'couldnt start anvil: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ethers-core/src/utils/anvil.rs:168:37


failures:
    can_abiencoderv2_output
    can_deploy_greeter
    can_handle_underscore_functions
    can_send_struct_param
```

This seems to work , if I install the latest version of foundry with Anvil install. AFAIK , it should be able to read Anvil from the util file and not need the installation

**Comment by mattsse** [comment]
do you have anvil installed?

https://github.com/foundry-rs/foundry#installation

we should add a note to ethers as well

**Comment by gakonst** [comment]
> This seems to work , if I install the latest version of foundry with Anvil install. AFAIK , it should be able to read Anvil from the util file and not need the installation

No - the `ethers_core::utils::Anvil` does not import Anvil as a dep, it uses it from the CLI which you must install
