### ISSUE TITLE
Ethers breaks serde, why?

### ISSUE THREAD

**Issue by WestXu** [gakonst/ethers-rs#2451]
**Version**

```
├── ethers v2.0.6
│   ├── ethers-addressbook v2.0.6
│   │   ├── ethers-core v2.0.6
│   ├── ethers-contract v2.0.6
│   │   ├── ethers-contract-abigen v2.0.6
│   │   │   ├── ethers-core v2.0.6 (*)
│   │   ├── ethers-contract-derive v2.0.6 (proc-macro)
│   │   │   ├── ethers-contract-abigen v2.0.6
│   │   │   │   ├── ethers-core v2.0.6 (*)
│   │   │   ├── ethers-core v2.0.6 (*)
│   │   ├── ethers-core v2.0.6 (*)
│   │   ├── ethers-providers v2.0.6
│   │   │   ├── ethers-core v2.0.6 (*)
│   ├── ethers-core v2.0.6 (*)
│   ├── ethers-etherscan v2.0.6
│   │   ├── ethers-core v2.0.6 (*)
│   ├── ethers-middleware v2.0.6
│   │   ├── ethers-contract v2.0.6 (*)
│   │   ├── ethers-core v2.0.6 (*)
│   │   ├── ethers-etherscan v2.0.6 (*)
│   │   ├── ethers-providers v2.0.6 (*)
│   │   ├── ethers-signers v2.0.6
│   │   │   ├── ethers-core v2.0.6 (*)
│   ├── ethers-providers v2.0.6 (*)
│   └── ethers-signers v2.0.6 (*)
```

**Description**

See this repo, only 10 lines of code:
https://github.com/WestXu/ethers-breaks-serde

Which panics unexpectedly:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a Decimal type representing a fixed-point number", line: 1, column: 9)', src/main.rs:10:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1113:23
   4: ad_hoc::main
             at ./src/main.rs:10:24
   5: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Deleting the `ethers = "2"` line from Cargo.toml fixes it.

**Comment by DaniPopes** [comment]
We enable `arbitrary_precision` for `serde_json` in `ethers-core`, which enables the feature everywhere, see [the cargo docs](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification). `rust-decimal` seems to have different serde features so you should look into those.

**Comment by gakonst** [comment]
Maybe we shouldn't enable the feature by default everywhere?

**Comment by WestXu** [comment]
Oh thanks for pointing me to the right direction. It indeed is caused by arbitrary_precision, and Decimal already has an additional feature flag [serde-arbitrary-precision](https://docs.rs/rust_decimal/latest/rust_decimal/#serde-arbitrary-precision) to deal with this exact situation. It surprised me as a seemingly bug of serde. Feel free to close this one.

**Comment by gakonst** [comment]
thx!
